version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=development
      - DATABASE=mongodb+srv://tejascanada2810:Cloud123@cloud-cluster.tyl5stu.mongodb.net/?retryWrites=true&w=majority&appName=Cloud-Cluster
      - PORT=8888
      - NODE_OPTIONS=--openssl-legacy-provider
      - JWT_SECRET=mern-crm
      - PUBLIC_SERVER_FILE="http://3.213.136.34:8888/"

    command: sh -c "npm run setup && npm run dev"

    networks:
      - server-mongo

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://3.213.136.34:8888/api
      - NODE_OPTIONS=--openssl-legacy-provider
      - VITE_BACKEND_SERVER="http://3.213.136.34:8888/"

    depends_on:
      - backend

networks:
  server-mongo:
